# filter job for only develop branch
develop-only: &develop-only
  filters:
    branches:
      only: develop

# filter job for only release branch
release-only: &release-only
  filters:
    branches:
      only: release

# filter job for protected branches
protected-only: &protected-only
  filters:
    branches:
      only:
        - master
        - develop
        - release
        - /feature[/].*/
        - /fix[/].*/
        - /chore[/]./
        - /deploy[/].*/


version: 2
jobs:
  build-artifacts: # Build dietstory jars  
    machine: true
    steps:
      - checkout # check out the code in the project directory
      - run: # Compile Diestory Project
          name: Compile DietStory
          command: |
            docker run --rm --env BUILD_SOURCE=local -v $(pwd):/mnt benjixd/dietstory-build
      - persist_to_workspace: # Persist required files for deployment
          root: ~/project
          paths:
            - cores
            - dist
            - wz

  deploy-develop: # Deploy artifacts to dev server
    machine: true
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            echo "Deploying to develop" && ls -lrt
      - run:
          name: Compress artifacts
          command: |
            zip -r dietstory.zip cores dist wz


# Workflows
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-artifacts:
          <<: *protected-only
      - deploy-develop:
          <<: *develop-only
          requires:
            - build-artifacts


